name: pdh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/landing_screen.jpg
    - assets/hillyxyz_Generate_a_background_image_for_a_personal_development_app._Theme_0e1e972b-4933-4004-94fa-23e1d21d8be7.png
    - assets/hillyxyz_Generate_a_background_image_for_a_personal_development_app._Theme_1b482d56-7423-46ca-8b2d-ea094e0e91f6.png
    - assets/hillyxyz_Generate_a_background_image_for_a_personal_development_app._Theme_03f6f05e-5f92-45f3-80d1-f08ada2fdfdc.png
    - assets/hillyxyz_Generate_a_background_image_for_a_personal_development_app._Theme_e3acd3c0-0b7d-4207-920f-391ae25d9690.png
