services:
  - type: web
    name: pdh-backend
    runtime: python3
    rootDir: backend   # 🔥 VERY IMPORTANT
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"

