import 'dart:developer' as developer;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:pdh/models/approved_goal_audit.dart';
import 'package:pdh/services/repository_service.dart';

class ApprovedGoalAuditService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final FirebaseAuth _auth = FirebaseAuth.instance;

  // Stream approved goals for current employee
  static Stream<List<ApprovedGoalAudit>> getEmployeeApprovedGoalsStream() {
    final uid = _auth.currentUser?.uid;
    if (uid == null) return Stream.value([]);
    return _firestore
        .collection('approved_goals_audit')
        .where('employeeId', isEqualTo: uid)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((s) => s.docs.map((d) => ApprovedGoalAudit.fromFirestore(d)).toList())
        .handleError((e) {
      developer.log('Error streaming approved goals: $e');
      return <ApprovedGoalAudit>[];
    });
  }

  // Stream approved goals for managers (all employees)
  static Stream<List<ApprovedGoalAudit>> getManagerApprovedGoalsStream() {
    return _firestore
        .collection('approved_goals_audit')
        .orderBy('timestamp', descending: true)
        .limit(500)
        .snapshots()
        .map((s) => s.docs.map((d) => ApprovedGoalAudit.fromFirestore(d)).toList())
        .handleError((e) {
      developer.log('Error streaming all approved goals: $e');
      return <ApprovedGoalAudit>[];
    });
  }

  // Log approved goal for audit trail
  static Future<void> logApprovedGoal({
    required String goalId,
    required String goalTitle,
    required String employeeId,
    required String employeeName,
    required String department,
    required String approvedBy,
    required String approvedByName,
  }) async {
    try {
      final audit = ApprovedGoalAudit(
        id: '', // Will be generated by Firestore
        goalId: goalId,
        goalTitle: goalTitle,
        employeeId: employeeId,
        employeeName: employeeName,
        department: department,
        approvedAt: DateTime.now(),
        approvedBy: approvedBy,
        approvedByName: approvedByName,
        timestamp: DateTime.now(),
      );

      // Add to Firestore audit collection
      await _firestore.collection('approved_goals_audit').add(audit.toFirestore());

      // Add to repository for offline persistence
      await RepositoryService.addApprovedGoalAudit(audit);

      developer.log('Approved goal audit logged: $goalId by $approvedByName');
    } catch (e) {
      developer.log('Error logging approved goal audit: $e');
      rethrow;
    }
  }

  // Sync offline audit entries when online
  static Future<void> syncOfflineAudits() async {
    try {
      await RepositoryService.syncApprovedGoalAudits();
      developer.log('Approved goal audits synced');
    } catch (e) {
      developer.log('Error syncing approved goal audits: $e');
    }
  }

  // Get audit by goal ID
  static Future<ApprovedGoalAudit?> getAuditByGoalId(String goalId) async {
    try {
      final snapshot = await _firestore
          .collection('approved_goals_audit')
          .where('goalId', isEqualTo: goalId)
          .limit(1)
          .get();
      
      if (snapshot.docs.isEmpty) return null;
      return ApprovedGoalAudit.fromFirestore(snapshot.docs.first);
    } catch (e) {
      developer.log('Error getting audit by goal ID: $e');
      return null;
    }
  }
}
