import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:pdh/services/database_service.dart';
import 'package:pdh/models/user_profile.dart';
import 'package:pdh/models/goal.dart';
import 'package:pdh/services/sample_data_seeder.dart';

class DatabaseTestScreen extends StatefulWidget {
  const DatabaseTestScreen({super.key});

  @override
  State<DatabaseTestScreen> createState() => _DatabaseTestScreenState();
}

class _DatabaseTestScreenState extends State<DatabaseTestScreen> {
  UserProfile? userProfile;
  List<Goal> goals = [];
  bool isLoading = false;
  String statusMessage = '';

  @override
  void initState() {
    super.initState();
    _loadUserData();
  }

  Future<void> _loadUserData() async {
    setState(() {
      isLoading = true;
      statusMessage = 'Loading user data...';
    });

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        final profile = await DatabaseService.getUserProfile(user.uid);
        final userGoals = await DatabaseService.getUserGoals(user.uid);
        
        setState(() {
          userProfile = profile;
          goals = userGoals;
          statusMessage = 'Data loaded successfully!';
        });
      } else {
        setState(() {
          statusMessage = 'No user logged in';
        });
      }
    } catch (e) {
      setState(() {
        statusMessage = 'Error loading data: $e';
      });
    } finally {
      setState(() {
        isLoading = false;
      });
    }
  }

  Future<void> _createSampleGoal() async {
    setState(() {
      isLoading = true;
      statusMessage = 'Creating sample goal...';
    });

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        final goal = Goal(
          id: '', // Will be generated by Firestore
          userId: user.uid,
          title: 'Test Goal - ${DateTime.now().millisecondsSinceEpoch}',
          description: 'This is a test goal created from the database test screen',
          category: GoalCategory.personal,
          priority: GoalPriority.medium,
          createdAt: DateTime.now(),
          targetDate: DateTime.now().add(const Duration(days: 7)),
          points: 50,
        );

        final goalId = await DatabaseService.createGoal(goal);
        setState(() {
          statusMessage = 'Sample goal created with ID: $goalId';
        });
        
        // Reload goals
        await _loadUserData();
      }
    } catch (e) {
      setState(() {
        statusMessage = 'Error creating goal: $e';
      });
    } finally {
      setState(() {
        isLoading = false;
      });
    }
  }

  Future<void> _createSampleGoals() async {
    setState(() {
      isLoading = true;
      statusMessage = 'Creating sample goals...';
    });

    try {
      final user = FirebaseAuth.instance.currentUser;
      if (user != null) {
        await SampleDataSeeder.createSampleGoals(user.uid);
        setState(() {
          statusMessage = 'Sample goals created successfully!';
        });
        
        // Reload goals
        await _loadUserData();
      }
    } catch (e) {
      setState(() {
        statusMessage = 'Error creating sample goals: $e';
      });
    } finally {
      setState(() {
        isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Database Test'),
        backgroundColor: const Color(0xFF1B2A40),
        foregroundColor: Colors.white,
      ),
      backgroundColor: const Color(0xFF0A0F1F),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Status Message
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: const Color(0xFF1B2A40),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Text(
                statusMessage,
                style: const TextStyle(color: Colors.white),
              ),
            ),
            
            const SizedBox(height: 20),
            
            // User Profile Section
            const Text(
              'User Profile',
              style: TextStyle(
                fontSize: 20,
                fontWeight: FontWeight.bold,
                color: Color(0xFFC7E3FF),
              ),
            ),
            const SizedBox(height: 10),
            
            if (userProfile != null) ...[
              _buildInfoCard('Email', userProfile!.email),
              _buildInfoCard('Display Name', userProfile!.displayName),
              _buildInfoCard('Total Points', userProfile!.totalPoints.toString()),
              _buildInfoCard('Level', userProfile!.level.toString()),
              _buildInfoCard('Badges', userProfile!.badges.length.toString()),
            ] else if (!isLoading) ...[
              const Text(
                'No user profile found',
                style: TextStyle(color: Colors.red),
              ),
            ],
            
            const SizedBox(height: 20),
            
            // Goals Section
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                 Text(
                  'Goals (${goals.length})',
                  style: TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFFC7E3FF),
                  ),
                ),
                Row(
                  children: [
                    ElevatedButton(
                      onPressed: isLoading ? null : _createSampleGoal,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFF6B4EE8),
                      ),
                      child: const Text('Add Goal'),
                    ),
                    const SizedBox(width: 8),
                    ElevatedButton(
                      onPressed: isLoading ? null : _createSampleGoals,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFF48A6ED),
                      ),
                      child: const Text('Add Sample Goals'),
                    ),
                  ],
                ),
              ],
            ),
            const SizedBox(height: 10),
            
            if (goals.isNotEmpty) ...[
              Expanded(
                child: ListView.builder(
                  itemCount: goals.length,
                  itemBuilder: (context, index) {
                    final goal = goals[index];
                    return Card(
                      color: const Color(0xFF1B2A40),
                      child: ListTile(
                        title: Text(
                          goal.title,
                          style: const TextStyle(color: Colors.white),
                        ),
                        subtitle: Text(
                          '${goal.category.name} • ${goal.status.name} • ${goal.progress}%',
                          style: const TextStyle(color: Colors.grey),
                        ),
                        trailing: Text(
                          '${goal.points} pts',
                          style: const TextStyle(
                            color: Color(0xFF48A6ED),
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    );
                  },
                ),
              ),
            ] else if (!isLoading) ...[
              const Text(
                'No goals found',
                style: TextStyle(color: Colors.grey),
              ),
            ],
            
            if (isLoading) ...[
              const Center(
                child: CircularProgressIndicator(
                  color: Color(0xFF48A6ED),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildInfoCard(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        children: [
          SizedBox(
            width: 120,
            child: Text(
              '$label:',
              style: const TextStyle(
                color: Color(0xFF8B9FB7),
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: const TextStyle(color: Colors.white),
            ),
          ),
        ],
      ),
    );
  }
}
