// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// Firebase project: pdh-v2. These options are the fallback when the app cannot
// fetch config from the backend (GET /firebase-config). Must match the backend
// FIREBASE_SERVICE_ACCOUNT_JSON project_id and, for web, FIREBASE_WEB_* env vars.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps (pdh-v2).
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wEmGpWnNfB03qNSsr2luFRZ6Fmo5e5Y',
    appId: '1:638896632756:web:6df76beff446f75ee378e1',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    authDomain: 'pdh-v2.firebaseapp.com',
    storageBucket: 'pdh-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUS2dYjMleU1EqQKy2fWAUViyA54yBoS0',
    appId: '1:638896632756:android:fe586c9180a35ec8e378e1',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    storageBucket: 'pdh-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuVGLc4Dx3wBVTd3ZubrUmtoqg7m187xc',
    appId: '1:638896632756:ios:d26381157f00b859e378e1',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    storageBucket: 'pdh-v2.firebasestorage.app',
    iosClientId: '638896632756-r9pcsombpf773efrm1c77ufrbt0uq2d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuVGLc4Dx3wBVTd3ZubrUmtoqg7m187xc',
    appId: '1:638896632756:ios:d26381157f00b859e378e1',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    storageBucket: 'pdh-v2.firebasestorage.app',
    iosClientId: '638896632756-r9pcsombpf773efrm1c77ufrbt0uq2d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9wEmGpWnNfB03qNSsr2luFRZ6Fmo5e5Y',
    appId: '1:638896632756:web:3ab9570e5c5eb3e1e378e1',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    authDomain: 'pdh-v2.firebaseapp.com',
    storageBucket: 'pdh-v2.firebasestorage.app',
  );

}