// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PDH-v2: Run "dart run flutterfire configure" and select PDH-v2 to fill the real Web appId from Firebase Console.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUS2dYjMleU1EqQKy2fWAUViyA54yBoS0',
    appId: '1:638896632756:web:000000000000000000000001',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    authDomain: 'pdh-v2.firebaseapp.com',
    storageBucket: 'pdh-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUS2dYjMleU1EqQKy2fWAUViyA54yBoS0',
    appId: '1:638896632756:android:fe586c9180a35ec8e378e1',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    storageBucket: 'pdh-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUS2dYjMleU1EqQKy2fWAUViyA54yBoS0',
    appId: '1:638896632756:ios:000000000000000000000001',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    storageBucket: 'pdh-v2.firebasestorage.app',
    iosBundleId: 'com.example.pdh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUS2dYjMleU1EqQKy2fWAUViyA54yBoS0',
    appId: '1:638896632756:ios:000000000000000000000001',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    storageBucket: 'pdh-v2.firebasestorage.app',
    iosBundleId: 'com.example.pdh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUS2dYjMleU1EqQKy2fWAUViyA54yBoS0',
    appId: '1:638896632756:web:000000000000000000000001',
    messagingSenderId: '638896632756',
    projectId: 'pdh-v2',
    authDomain: 'pdh-v2.firebaseapp.com',
    storageBucket: 'pdh-v2.firebasestorage.app',
  );
}
