// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjg19Ej8fbUOfa6WYlEX-b4CNi-y0Lozc',
    appId: '1:565445962523:web:a987a77ea9633d308401be',
    messagingSenderId: '565445962523',
    projectId: 'pdh-fe6eb',
    authDomain: 'pdh-fe6eb.firebaseapp.com',
    storageBucket: 'pdh-fe6eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAfySsOd2h0jCj5m3v3vIR9d0ys7kmKk',
    appId: '1:565445962523:android:96cfa7d317c670c98401be',
    messagingSenderId: '565445962523',
    projectId: 'pdh-fe6eb',
    storageBucket: 'pdh-fe6eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-UKlI3NI-1ktNofSXsqSBHbjG8EQ3XcA',
    appId: '1:565445962523:ios:7561461d42d085888401be',
    messagingSenderId: '565445962523',
    projectId: 'pdh-fe6eb',
    storageBucket: 'pdh-fe6eb.firebasestorage.app',
    iosBundleId: 'com.example.pdh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-UKlI3NI-1ktNofSXsqSBHbjG8EQ3XcA',
    appId: '1:565445962523:ios:7561461d42d085888401be',
    messagingSenderId: '565445962523',
    projectId: 'pdh-fe6eb',
    storageBucket: 'pdh-fe6eb.firebasestorage.app',
    iosBundleId: 'com.example.pdh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjg19Ej8fbUOfa6WYlEX-b4CNi-y0Lozc',
    appId: '1:565445962523:web:5baabea0d2d8ce3f8401be',
    messagingSenderId: '565445962523',
    projectId: 'pdh-fe6eb',
    authDomain: 'pdh-fe6eb.firebaseapp.com',
    storageBucket: 'pdh-fe6eb.firebasestorage.app',
  );
}
