// This file is auto-generated during build time from Render environment variables
// DO NOT edit this file manually - it will be overwritten during build
// 
// For local development, create a .env file with:
// ENCRYPTION_KEY=your_key_here
// JWT_SECRET_KEY=your_key_here
//
// For production on Render, set these as environment variables in Render dashboard

class EnvConfig {
  // Encryption key for Fernet decryption (must match Khonobuzz backend)
  // This will be injected during build from ENCRYPTION_KEY environment variable
  static const String? encryptionKey = null;
  
  // JWT secret key for token verification (must match Khonobuzz backend)
  // This will be injected during build from JWT_SECRET_KEY environment variable
  static const String? jwtSecretKey = null;
  
  static const String? backendUrl = null;
  
  // Check if encryption is configured
  static bool get isEncryptionConfigured => encryptionKey != null && encryptionKey!.isNotEmpty;
  
  // Check if JWT verification is configured
  static bool get isJwtVerificationConfigured => jwtSecretKey != null && jwtSecretKey!.isNotEmpty;
}

