#!/bin/bash
# Script to inject environment variables into Flutter web build
# This script creates a config.dart file with environment variables from Render

# Don't use set -e, we want to continue even if some steps fail
set +e

CONFIG_FILE="lib/config/env_config.dart"
CONFIG_DIR="lib/config"

# Create the config directory if it doesn't exist
mkdir -p "$CONFIG_DIR"

# Ensure the file exists (create placeholder if it doesn't)
if [ ! -f "$CONFIG_FILE" ]; then
  echo "⚠️  Config file doesn't exist, creating placeholder..."
  cat > "$CONFIG_FILE" << 'PLACEHOLDER'
// This file is auto-generated during build time
// DO NOT edit this file manually - it will be overwritten during build

class EnvConfig {
  static const String? encryptionKey = null;
  static const String? jwtSecretKey = null;
  static bool get isEncryptionConfigured => encryptionKey != null && encryptionKey!.isNotEmpty;
  static bool get isJwtVerificationConfigured => jwtSecretKey != null && jwtSecretKey!.isNotEmpty;
}
PLACEHOLDER
fi

# Get environment variables from Render (or use defaults for local dev)
ENCRYPTION_KEY="${ENCRYPTION_KEY:-}"
JWT_SECRET_KEY="${JWT_SECRET_KEY:-}"

# Generate the config file
cat > "$CONFIG_FILE" << EOF
// This file is auto-generated during build time
// DO NOT commit this file with actual keys - it's generated from environment variables
// Environment variables are injected from Render dashboard during build

class EnvConfig {
  // Encryption key for Fernet decryption (must match Khonobuzz backend)
  static const String? encryptionKey = $([ -n "$ENCRYPTION_KEY" ] && echo "\"$ENCRYPTION_KEY\"" || echo "null");
  
  // JWT secret key for token verification (must match Khonobuzz backend)
  static const String? jwtSecretKey = $([ -n "$JWT_SECRET_KEY" ] && echo "\"$JWT_SECRET_KEY\"" || echo "null");
  
  // Check if encryption is configured
  static bool get isEncryptionConfigured => encryptionKey != null && encryptionKey!.isNotEmpty;
  
  // Check if JWT verification is configured
  static bool get isJwtVerificationConfigured => jwtSecretKey != null && jwtSecretKey!.isNotEmpty;
}
EOF

if [ -n "$ENCRYPTION_KEY" ]; then
  echo "✅ ENCRYPTION_KEY injected (length: ${#ENCRYPTION_KEY} chars)"
else
  echo "⚠️  ENCRYPTION_KEY not set - token decryption will not work"
fi

if [ -n "$JWT_SECRET_KEY" ]; then
  echo "✅ JWT_SECRET_KEY injected (length: ${#JWT_SECRET_KEY} chars)"
else
  echo "⚠️  JWT_SECRET_KEY not set - JWT verification will not work"
fi

echo "✅ Environment variables injected into $CONFIG_FILE"

